version: "3"
services:
  mongodb-container-one:
    image: mongo:latest
    container_name: "mongodb-container-one"
    ports:
      - 28000:27017
  springboot-with-mongodb-container-one:
    image: sassy14/dockertp:spbootimg2
    container_name: springboot-with-mongodb-container-one
    ports:
      - 8090:8089
    links:
      - mongodb-container-one